### ISSUE TITLE
Issue with Submission, and Question about Ponderation of Scores & Timeline 

### ISSUE THREAD

**Issue by oscarloch** [Stanford-AIMI/RRG24#11]
1. I have submitted a second entry that was marked as accepted, but it does not appear on the leaderboard. I suspect this may be due to the second submission yielding lower scores than my initial one. How are instances like these typically addressed, particularly when the second submission performs worse than the first? Could this be the reason for its absence, or might there be another explanation?

2. How will the scores (BLEU4, ROUGE-L, Bertscore, F1-cheXbert, F1-RadGraph) be weighted to determine rankings?

3. Previously, the deadline for System submissions was May 10th, with papers due by May 17th. However, the submission deadline has been extended to May 15th. Will the deadline for System papers remain unchanged, or will it be postponed accordingly?
![322896404-7f247ae3-de52-4369-9d9b-8e94f052a720](https://github.com/Stanford-AIMI/RRG24/assets/69605823/59c321cf-9966-46af-a50a-bb6933ce9dd6)

Thank you very much!

**Comment by jbdel** [comment]
Thanks for your comment.

You are right for 1., only your best score, according to f1radgraph, will be shown. You can retrieve all your submissions using the "retrieve" section.
2. F1-radgraph will be used to determine ranking, but our overview paper will report all the metrics.
3. The deadline for system papers will remain unchanged, unless communicated otherwise by the workshop organizer. Will keep you updated.
thanks,
